"""Compare Experiment A (baseline) and Experiment B (RDD-YOLO) from their real outputs.

Reads  experiments/<run>/eval_test/metrics.json  and  experiments/<run>/results.csv
Writes experiments/comparison.json, experiments/comparison.md and
       experiments/comparison_curves.png, experiments/comparison_metrics.png

Usage:
    .venv\\Scripts\\python training\\compare.py --baseline baseline_yolo26n --rdd rdd_yolo26n
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from rdd_yolo.constants import CLASS_CODES, EXPERIMENTS_DIR  # noqa: E402

METRICS = [("precision", "Precision"), ("recall", "Recall"), ("f1", "F1"), ("mAP50", "mAP@50"),
           ("mAP50_95", "mAP@50-95")]


def load(run: str, split: str) -> tuple[dict, list[dict]]:
    mfile = EXPERIMENTS_DIR / run / f"eval_{split}" / "metrics.json"
    if not mfile.exists():
        sys.exit(f"Missing {mfile}. Run training/evaluate.py --run {run} first.")
    rows = list(csv.DictReader((EXPERIMENTS_DIR / run / "results.csv").open()))
    rows = [{k.strip(): float(v) for k, v in r.items()} for r in rows]
    return json.loads(mfile.read_text()), rows


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # Windows consoles default to cp1252
    ap = argparse.ArgumentParser()
    ap.add_argument("--baseline", default="baseline_yolo26n")
    ap.add_argument("--rdd", default="rdd_yolo26n")
    ap.add_argument("--split", default="test")
    args = ap.parse_args()

    a, ra = load(args.baseline, args.split)
    b, rb = load(args.rdd, args.split)

    def delta(x, y):
        return y - x

    table = {
        "split": args.split, "baseline_run": args.baseline, "rdd_run": args.rdd,
        "overall": {k: {"baseline": a["overall"][k], "rdd": b["overall"][k],
                        "delta": delta(a["overall"][k], b["overall"][k])} for k, _ in METRICS},
        "per_class_mAP50": {c: {"baseline": a["per_class"].get(c, {}).get("mAP50"),
                                "rdd": b["per_class"].get(c, {}).get("mAP50")} for c in CLASS_CODES},
        "per_class_mAP50_95": {c: {"baseline": a["per_class"].get(c, {}).get("mAP50_95"),
                                   "rdd": b["per_class"].get(c, {}).get("mAP50_95")} for c in CLASS_CODES},
        "efficiency": {
            "parameters": {"baseline": a["parameters"], "rdd": b["parameters"]},
            "gflops": {"baseline": a["gflops"], "rdd": b["gflops"]},
            "model_size_mb": {"baseline": a["model_size_mb"], "rdd": b["model_size_mb"]},
            "fps_end_to_end": {"baseline": a["speed_benchmark"]["fps_end_to_end"],
                               "rdd": b["speed_benchmark"]["fps_end_to_end"]},
            "inference_ms": {"baseline": a["speed_benchmark"]["inference_ms_mean"],
                             "rdd": b["speed_benchmark"]["inference_ms_mean"]},
        },
        "epochs": {"baseline": len(ra), "rdd": len(rb)},
    }
    (EXPERIMENTS_DIR / "comparison.json").write_text(json.dumps(table, indent=2))

    lines = [f"# Baseline vs RDD-YOLO ({args.split} split)", "",
             "Generated by `training/compare.py` from real evaluation outputs.", "",
             "| Metric | Baseline YOLO26 | RDD-YOLO | Δ (RDD − Base) |", "|---|---|---|---|"]
    for k, label in METRICS:
        o = table["overall"][k]
        lines.append(f"| {label} | {o['baseline']:.4f} | {o['rdd']:.4f} | {o['delta']:+.4f} |")
    e = table["efficiency"]
    lines += [f"| Parameters | {e['parameters']['baseline']:,} | {e['parameters']['rdd']:,} | "
              f"{e['parameters']['rdd'] - e['parameters']['baseline']:+,} |",
              f"| GFLOPs | {e['gflops']['baseline']} | {e['gflops']['rdd']} | |",
              f"| Model size (MB) | {e['model_size_mb']['baseline']} | {e['model_size_mb']['rdd']} | |",
              f"| FPS (end-to-end, batch 1) | {e['fps_end_to_end']['baseline']} | {e['fps_end_to_end']['rdd']} | |",
              f"| Epochs trained | {len(ra)} | {len(rb)} | |", "",
              "## Per-class mAP@50 / mAP@50-95", "", "| Class | Base mAP50 | RDD mAP50 | Base mAP50-95 | RDD mAP50-95 |",
              "|---|---|---|---|---|"]
    for c in CLASS_CODES:
        p50, p95 = table["per_class_mAP50"][c], table["per_class_mAP50_95"][c]
        fmt = lambda v: f"{v:.4f}" if v is not None else "n/a"  # noqa: E731
        lines.append(f"| {c} | {fmt(p50['baseline'])} | {fmt(p50['rdd'])} | {fmt(p95['baseline'])} | {fmt(p95['rdd'])} |")
    (EXPERIMENTS_DIR / "comparison.md").write_text("\n".join(lines) + "\n", encoding="utf-8")

    import matplotlib

    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig, axes = plt.subplots(2, 2, figsize=(11, 7))
    for ax, (key, title) in zip(axes.flat, [("train/box_loss", "Train box loss"), ("val/box_loss", "Val box loss"),
                                            ("metrics/mAP50(B)", "Val mAP@50"), ("metrics/mAP50-95(B)", "Val mAP@50-95")]):
        for rows, label in ((ra, "Baseline"), (rb, "RDD-YOLO")):
            if rows and key in rows[0]:
                ax.plot([r["epoch"] for r in rows], [r[key] for r in rows], label=label)
        ax.set_title(title)
        ax.set_xlabel("epoch")
        ax.grid(alpha=0.3)
        ax.legend()
    fig.tight_layout()
    fig.savefig(EXPERIMENTS_DIR / "comparison_curves.png", dpi=140)
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(8, 4))
    xs = range(len(METRICS))
    ax.bar([x - 0.2 for x in xs], [a["overall"][k] for k, _ in METRICS], 0.4, label="Baseline")
    ax.bar([x + 0.2 for x in xs], [b["overall"][k] for k, _ in METRICS], 0.4, label="RDD-YOLO")
    ax.set_xticks(list(xs), [lbl for _, lbl in METRICS])
    ax.set_title(f"{args.split} split metrics")
    ax.legend()
    fig.tight_layout()
    fig.savefig(EXPERIMENTS_DIR / "comparison_metrics.png", dpi=140)
    plt.close(fig)
    print("\n".join(lines))


if __name__ == "__main__":
    main()
